import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ChevronLeft } from 'lucide-react';
const StockDetail = () => {
    const { symbol } = useParams(); // URL에서 종목 코드 추출
    const navigate = useNavigate();
    const [activeTab, setActiveTab] = useState('차트·호가');
    const tabs = ['차트·호가', '종목정보', '뉴스·공시', '거래현황', '커뮤니티'];
    return (_jsxs("div", { className: "flex flex-col h-screen bg-[#0E1013] text-white", children: [_jsxs("header", { className: "flex items-center p-4 border-b border-white/5", children: [_jsx("button", { onClick: () => navigate(-1), className: "p-2 hover:bg-white/5 rounded-full", children: _jsx(ChevronLeft, { size: 24 }) }), _jsxs("div", { className: "ml-4", children: [_jsx("h1", { className: "text-lg sm:text-xl font-bold", children: symbol || '삼성전자' }), _jsx("p", { className: "text-sm text-slate-400", children: "005930 \u00B7 KOSPI" })] })] }), _jsx("nav", { className: "flex px-4 border-b border-white/5", children: tabs.map((tab) => (_jsxs("button", { onClick: () => setActiveTab(tab), className: `px-4 py-4 text-sm font-medium transition-all relative ${activeTab === tab ? 'text-blue-500' : 'text-slate-400 hover:text-slate-200'}`, children: [tab, activeTab === tab && (_jsx("div", { className: "absolute bottom-0 left-0 right-0 h-0.5 bg-blue-500" }))] }, tab))) }), _jsxs("main", { className: "flex-1 overflow-y-auto p-4 md:p-10 pb-24", children: [activeTab === '차트·호가' && _jsx(ChartSection, {}), activeTab === '종목정보' && _jsx(InfoSection, {}), activeTab === '뉴스·공시' && _jsx(NewsSection, {}), activeTab === '거래현황' && _jsx(TradeSection, {}), activeTab === '커뮤니티' && _jsx(CommunitySection, {})] })] }));
};
// --- 각 섹션 컴포넌트 ---
const ChartSection = () => (_jsxs("div", { className: "space-y-6", children: [_jsx("div", { className: "h-64 bg-[#16191C] rounded-3xl flex items-center justify-center border border-white/5", children: _jsx("p", { className: "text-slate-500", children: "\uCC28\uD2B8\uAC00 \uB4E4\uC5B4\uAC08 \uC790\uB9AC\uC785\uB2C8\uB2E4 (Recharts \uC801\uC6A9)" }) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsx("div", { className: "p-6 bg-[#16191C] rounded-3xl border border-white/5 text-center text-red-500 font-bold text-lg", children: "\uB9E4\uB3C4 \uD638\uAC00" }), _jsx("div", { className: "p-6 bg-[#16191C] rounded-3xl border border-white/5 text-center text-blue-500 font-bold text-lg", children: "\uB9E4\uC218 \uD638\uAC00" })] })] }));
const InfoSection = () => (_jsxs("div", { className: "bg-[#16191C] p-6 rounded-3xl border border-white/5 space-y-4", children: [_jsxs("div", { className: "flex justify-between border-b border-white/5 pb-2", children: [_jsx("span", { className: "text-slate-400", children: "\uC2DC\uAC00\uCD1D\uC561" }), _jsx("span", { className: "font-bold", children: "465\uC870 6,431\uC5B5" })] }), _jsxs("div", { className: "flex justify-between border-b border-white/5 pb-2", children: [_jsx("span", { className: "text-slate-400", children: "PER" }), _jsx("span", { className: "font-bold", children: "35.21\uBC30" })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-slate-400", children: "\uBC30\uB2F9\uC218\uC775\uB960" }), _jsx("span", { className: "font-bold", children: "2.1%" })] })] }));
const NewsSection = () => (_jsx("div", { className: "space-y-4", children: [1, 2, 3].map((n) => (_jsxs("div", { className: "p-4 hover:bg-white/5 rounded-2xl transition-all cursor-pointer border-b border-white/5", children: [_jsx("h4", { className: "font-medium text-slate-200", children: "\uC0BC\uC131\uC804\uC790, \uC5ED\uB300\uAE09 \uC2E4\uC801 \uBC1C\uD45C \uC608\uC815... \uBC18\uB3C4\uCCB4 \uBD80\uBB38 \uD751\uC790 \uC804\uD658" }), _jsx("p", { className: "text-xs text-slate-500 mt-2", children: "\uACBD\uC81C\uC2E0\uBB38 \u00B7 1\uC2DC\uAC04 \uC804" })] }, n))) }));
const TradeSection = () => (_jsx("div", { className: "bg-[#16191C] rounded-3xl overflow-hidden border border-white/5 text-sm", children: _jsxs("table", { className: "w-full text-left", children: [_jsx("thead", { className: "bg-white/5 text-slate-400", children: _jsxs("tr", { children: [_jsx("th", { className: "p-4", children: "\uC2DC\uAC04" }), _jsx("th", { className: "p-4 text-right", children: "\uCCB4\uACB0\uAC00" }), _jsx("th", { className: "p-4 text-right", children: "\uAC70\uB798\uB7C9" })] }) }), _jsx("tbody", { className: "divide-y divide-white/5", children: [1, 2, 3, 4, 5].map((i) => (_jsxs("tr", { children: [_jsx("td", { className: "p-4 text-slate-400", children: "15:30:02" }), _jsx("td", { className: "p-4 text-right font-medium", children: "78,200" }), _jsx("td", { className: "p-4 text-right text-red-500", children: "1,240" })] }, i))) })] }) }));
const CommunitySection = () => {
    const [comment, setComment] = useState('');
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-[#16191C] p-4 rounded-2xl border border-white/5", children: [_jsx("textarea", { value: comment, onChange: (e) => setComment(e.target.value), placeholder: "\uC8FC\uC8FC\uB4E4\uACFC \uC758\uACAC\uC744 \uB098\uB220\uBCF4\uC138\uC694", className: "w-full bg-transparent outline-none resize-none h-24 text-sm" }), _jsx("div", { className: "flex justify-end mt-2", children: _jsx("button", { className: "px-4 py-2 bg-blue-600 rounded-full font-bold text-sm hover:bg-blue-500 transition-all", children: "\uB4F1\uB85D" }) })] }), _jsx("div", { className: "space-y-4", children: _jsxs("div", { className: "p-4 bg-white/5 rounded-2xl", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2 text-xs text-slate-500 font-medium", children: [_jsx("div", { className: "w-6 h-6 bg-slate-700 rounded-full flex items-center justify-center text-[10px]", children: "\uC775\uBA85" }), _jsx("span", { children: "3\uBD84 \uC804" })] }), _jsx("p", { className: "text-sm", children: "\uC0BC\uC804 8\uB9CC \uC804\uC790 \uAC00\uC988\uC544!!" })] }) })] }));
};
export default StockDetail;
